// ── 新UIの文言辞書（R50提案2c） ──────────────────────────────────
// iso 層内の pure モジュール（DOM・通信・時刻・乱数に触らない）。
// 言語は office_json の lang が正本（apply が setLang する）。データ到着前は
// navigator.language で仮判定する。
//
// 掟: ja の値は既存スモーク（ops/admin/onboard）が文言をピンしているので
//     「1字も変えない」。変えるならスモークとセットで。
let LANG = (typeof navigator !== "undefined" &&
  String(navigator.language || "").toLowerCase().startsWith("ja")) ? "ja" : "en";

export function setLang(l) {
  LANG = l === "en" ? "en" : "ja";
}

export function lang() {
  return LANG;
}

const DICT = {
  ja: {
    // ゾーン
    zone_desk: "自席で作業", zone_meeting: "会議中", zone_queue: "あなた待ち",
    zone_lounge: "休憩中", zone_external: "外部 (OpenClaw)",
    // R90-U2: プロジェクトボード・1行の概況（用語は プロジェクト/セッション/サブエージェント の3語）
    board_title: "プロジェクト",
    digest_title: "留守中のダイジェスト",
    digest_retained: "留守中のダイジェスト（記録は直近90日）",
    digest_stopped: (n, m) => `❗ 止まっている: ${n}体（うち最長 ${m}分）`,
    digest_completed: (n) => `✅ 終わった: ${n}件`,
    digest_working: (n) => `▶ 動いている: ${n}件`,
    digest_strip: (away, stopped, done, working) =>
      `留守中 ${away}: ❗${stopped} ✅${done} ▶${working} — 詳しく`,
    digest_today: "今日",
    digest_details: "詳しく — 20秒リプレイ",
    digest_close: "ダイジェストを閉じる（Esc）",
    digest_seen_failed: "既読を保存できませんでした。次の接続時にもう一度表示されることがあります。",
    replay_progress: "20秒リプレイの進捗",
    replay_pause: "一時停止", replay_resume: "再開",
    replay_close: "リプレイを閉じて現在に戻る（Esc）",
    replay_empty: "この期間に再生できるイベントはありません。",
    replay_failed: "リプレイを読み込めませんでした。もう一度お試しください。",
    replay_latest: (n) => `最新の最大${n}件を再生します。`,
    growth_details: "XPの内訳を開く",
    growth_total: (xp) => `${xp} XP`,
    growth_tasksDone: (n, xp) => `完了 ${n}×10 = ${xp} XP`,
    growth_commits: (n, xp) => `コミット ${n}×5 = ${xp} XP`,
    growth_asksAnswered: (n, xp) => `❗回答 ${n}×2 = ${xp} XP`,
    growth_fastAnswers: (n, xp) => `5分以内の回答ボーナス ${n}×1 = ${xp} XP`,
    growth_activeMin: (n, xp) => `稼働 ${n}分÷5 = ${xp} XP`,
    growth_hires: (n, xp) => `雇用 ${n}×5 = ${xp} XP`,
    growth_turnsCompleted: (n, xp) => `Codexターン完了 ${n}×3 = ${xp} XP`,
    growth_other: (key, n, xp) => `${key} ${n}: ${xp} XP`,
    growth_no_tokens: "XPは表示した内訳のみ。トークン量は含みません。",
    growth_unavailable: "内訳はこの接続では取得できません。ローカルのオフィスで確認できます。",
    growth_project: "プロジェクト",
    growth_level_up: (name, level) => `${name} が Lv ${level} になりました`,
    board_summary: (n, work, queue, rest) =>
      `${n}セッション出勤 — 作業${work} · あなた待ち${queue} · 休憩${rest}`,
    board_count: (n) => `${n}件`,
    board_session: (n) => `セッション ${n}`,
    board_level: (n) => `Lv ${n}`,
    board_window_5h: "5h",
    board_working: "作業", board_attention: "あなた待ち",
    board_waiting: "待機", board_resting: "休憩",
    board_no_detail: "詳細なし",
    board_vendor_claude: "Claude", board_vendor_codex: "Codex",
    board_vendor_openclaw: "OpenClaw", board_vendor_other: "その他",
    // 静的クローム
    office_fallback: "AIオフィス",
    loading: "読み込み中…",
    gauge_credits: "クレジット消費",
    gauge_money: "コスト（参考）",
    btn_newproj: "➕ 新プロジェクト",
    btn_hire: "＋ セッションを1つ増やす",
    hire_where: "① どこで",
    hire_choose: "最近のプロジェクトを選ぶ",
    hire_pick: "フォルダを選ぶ",
    hire_picked: "選んだフォルダ",
    hire_pick_note: "過去に Claude で開いたフォルダを選んでください。初めてのフォルダは、先にそこで claude を起動すると選べるようになります（反映まで約1分）。",
    hire_pick_failed: "フォルダは選択されませんでした。もう一度選べます。",
    hire_what: "② 何を",
    hire_prompt: "1行の指示（1〜4000字）",
    hire_count: (n) => `${n} / 4000字`,
    hire_worktree: "別ブランチで隔離",
    hire_who: "③ 誰に",
    hire_claude: "Claude（既定）",
    hire_codex: "Codex — Terminal から操作",
    hire_go: "セッションを起動する",
    hire_starting: "起動しています…",
    hire_started: "起動しました。入口から出勤するまで少しお待ちください。",
    hire_failed: "起動を確認できませんでした。セッション一覧を確認し、未起動なら登録済みのフォルダと claude の設定を確認してから再試行してください。",
    hire_terminal_note: "Terminal を開くには、次のコマンドを手元のターミナルで実行してください。Codex への指示はそこで入力できます。",
    hire_terminal_cmd: "open -a Terminal",
    hire_terminal_copy: "Terminal を開くコマンドをコピー",
    hire_terminal_copied: "コピーしました。手元のターミナルに貼り付けて実行してください。",
    hire_new_badge: "🆕",
    hire_branch_badge: (slug) => `⎇ ${slug}`,
    onboarding_questions: "❗が出たら数字キーで答えられます",
    onboarding_dismiss: "❗が出たら数字キーで答えられます（クリックで閉じる）",
    setup_checklist: "📱 接続チェック",
    setup_hooks_ready: "✓ フックは配線済み",
    setup_hooks_pending: "○ フックは未配線",
    setup_events_ready: "✓ イベント記録は配線済み",
    setup_events_pending: "○ イベント記録は未配線",
    setup_events_unknown: "○ イベント記録は未確認",
    no3d_list: "一覧モードで開く",
    btn_pair: "📱 スマホ連携",
    btn_run: "▶ スマホから実行できる操作",
    no3d: "この環境では3D表示を利用できません（グラフィックス機能が無効）。左の一覧から、いつもどおり確認と指示ができます。",
    tpl_title: "⚡ 定型文",
    tpl_note: "よく使う指示を保存 — ここと📱スマホからワンタップで投函できます（最大8件・120字）",
    tpl_label_ph: "ラベル（例: ビルド確認）",
    tpl_text_ph: "送る本文（例: verifyを回して結果を1行で報告）",
    tpl_add_row: "追加",
    tpl_save: "保存",
    tpl_del: "削除",
    tpl_saved: "定型文を保存しました（スマホにも同期されます）",
    run_head: "▶ スマホから実行できる操作",
    run_note: "スマホから実行できるコマンドをここで登録します。安全のため、スマホ側からは追加も編集もできません（登録済みのものを実行できるだけ）。",
    run_empty: "まだ登録がありません。下の「例を入れる」を押すと、そのまま使える雛形が入ります。",
    run_hint: "argv は配列（shell文字列は不可）・cwd は絶対パス・returnOutput は none|tail|full（既定 none＝出力を中継に出しません）。",
    run_save: "保存",
    run_sample: "例を入れる",
    run_sample_label: "gitの状態を見る",
    run_sample_note: "cwd（作業フォルダ）を自分のプロジェクトのパスに書き換えてから保存してください。",
    run_saved: "保存しました",
    btn_res: "⚡ リソース",
    // R85-3: PC機能パリティ（▶起動・⚙設定・📡中継・💱為替）
    btn_launch: "▶ プロジェクト起動",
    launch_note: "直近に開いたプロジェクトを Terminal で起動します（スマホの▶と同じ一覧）。",
    launch_empty: "起動できるプロジェクトがまだありません（claude を一度起動すると載ります）。",
    launch_ok: (n) => `▶ ${n} を起動しました`,
    btn_settings: "⚙ 設定",
    stream_copy: "🎥 配信用URLをコピー",
    stream_obs: "OBS用（16:9）", stream_short: "ショート用（9:16）", stream_monitor: "セカンドモニタ用",
    stream_copied: "配信用URLをコピーしました",
    stream_copy_failed: "URLをコピーできませんでした。ブラウザのクリップボード許可を確認してください。",
    stream_now: (text) => `いま: ${text}`,
    stream_waiting: "待機中", stream_resting: "休憩中", stream_empty: "セッションの出勤を待っています",
    replay_save: "今日のリプレイを保存（20秒 WebM）",
    replay_record_failed: "リプレイを保存できませんでした。もう一度お試しください。",
    replay_record_cancelled: "録画を中止しました。画面を表示したまま保存してください。",
    replay_saved: "リプレイを保存しました",
    set_theme: "🌙 テーマ",
    set_theme_light: "ライト",
    set_theme_dark: "ダーク",
    set_lang: "🌐 言語",
    relay_head: "📡 スマホ中継",
    relay_today: "今日の使用量",
    relay_slowed: "（減速中）",
    relay_throttled: "（自動減速中）",
    fx_label: "💱 円換算レート（¥/$）",
    fx_save: "保存",
    fx_saved: "💱 レートを保存しました",
    snd_title: "通知音",
    sound_ask: "音で知らせますか？", sound_yes: "音をONにする", sound_no: "今後は聞かない",
    sound_on: "ON", sound_off: "OFF",
    camera_title: "配置", camera_compact: "コンパクト", camera_standard: "標準", camera_stream: "配信向け",
    reply_options: "返信の操作", reply_save: "この返信を定型に保存",
    tpl_existing: (n) => `保存済みの定型文（${n}件）`, tpl_invalid: "名前と本文を入力してください。保存できる定型文は8件までです。",
    arch_title: "帽子・アクセサリ", arch_none: "なし", arch_phones: "ヘッドホン", arch_cap: "キャップ",
    arch_beret: "ベレー帽", arch_pencil: "鉛筆", arch_bowtie: "蝶ネクタイ", arch_mortar: "角帽",
    arch_headset: "ヘッドセット", arch_hardhat: "ヘルメット", arch_eyeshade: "アイシェード",
    arch_readonly: "この表示ではアクセサリを変更できません。", arch_chat: "会話を開く",
    term_title: "実ターミナルを前面に表示（ロボのダブルクリックでも）",
    term_ok: (app) => `🖥 ${app} を前面に出しました`,
    term_none: "このプロジェクトにローカルターミナルはありません",
    woke: (n) => `▶ ${n} が指示を受け取り動き出しました`,
    attn_resolved: (n) => `✅ ${n} の❗が解消しました`,
    work_head: "📋 いまの仕事",
    qb_head: "⚡ 定型",
    keys_head: "🔑 アカウント連携",
    keys_connect: "接続",
    keys_change: "変更",
    keys_save: "保存",
    keys_saved: "🔑 保存しました",
    keys_ph: "キーを貼り付け（20文字以上）",
    keys_grp_auto: "🅰 自動でつながる（設定不要）",
    keys_grp_auto_sub: "ターミナルでログインして使うだけで、消費が自動で記録されます。",
    keys_grp_key: "🅱 APIキーでつなぐ",
    keys_grp_key_sub: "各サービスのAPIキーを貼ると、残高・消費を自動取得します。",
    keys_badge_auto: "自動",
    keys_now: (e) => `いま: ${e}`,
    keys_getfrom: (u) => `発行: ${u}`,
    keys_revoke: "解除",
    keys_revoke_arm: "もう一度で解除",
    keys_revoked: "🔑 解除しました",
    gauges_title: "クリックで連携・台帳を開く",
    sending: "送信中…",
    sending_busy: "送信中です — 少し待ってください",
    updated_ago: (s) => `更新 ${s}秒前`,
    hist_more: (n) => `ほか ${n} 件`,
    compose_ph: "このプロジェクトへ指示を書いて Enter",
    card_tasks: "タスクの進み",
    card_today: "今日のオフィス",
    today_sent: "送った指示",
    today_attn: "対応まち",
    today_working: "作業中",
    today_resting: "休憩中",
    today_none: "まだ指示を送っていません",
    today_last: (a) => `最後の指示 ${a}`,
    unit_items: "件",
    unit_people: "人",
    card_hist: "最近の指示",
    card_agents: "プロジェクト",
    // 送信・トースト
    demo_no_send: "🎬 デモモード — 投函は行われません",
    deliver_ok: (n) => `📨 ${n} へ配達しました`,
    deliver_saved: (n) => `📨 ${n} へ保存しました — そのターミナルを次に触った瞬間に届きます`,
    send_stalled: (n, m) => `⌨️ 送信から${m}分、${n} は動いていません — ターミナルを確認してください`,
    deliver_fail: (m) => `配達失敗: ${m}`,
    reg_fail: (m) => `登録失敗: ${m}`,
    // humanSummary（シートの1文）
    hs_doing: (act) => `いま「${act}」を進めています。`,
    hs_question: "質問があり、あなたの回答を待っています。",
    hs_approval: (min) => `${min}分、同じ操作のまま止まっています。ここから返信できますが、ターミナルに許可の確認が出ている場合はそちらで答える必要があります。`,
    hs_meeting: (n) => `サブエージェント${n}体と会議中です。`,
    hs_lounge: "作業が一段落して、ラウンジで休憩中です。",
    hs_external: "別のMac（OpenClaw）で動いている外部のプロジェクトです。",
    hs_working: "作業中です。",
    hs_waiting: "次の指示を待っています。",
    // ❗トレイ・回答定型文（セッションへ送る本文も言語連動）
    approval_min: (m) => `${m}分 止まっています`,
    attn_target: (w) => `対象: ${w}`,
    opt_text: (label) => `選択肢「${label}」でお願いします。`,
    // R86-H: いま実際に聞かれている（承認フックが待っている）ときの文言
    answer_sent: (n) => `✅ ${n} に回答が届きました（ターミナルが動き出します）`,
    allow_sent: (n) => `✅ ${n} の操作を許可しました`,
    ask_live: "いまターミナルで返事を待っています。ここから答えればすぐ届きます。",
    ask_perm: (tool, what) =>
      `ターミナルで ${tool} の実行許可を待っています${what ? `: ${what}` : ""}`,
    opt_allow: "✅ 許可する",
    opt_refuse: "許可しない",
    opt_refuse_text: "この操作は許可しません。別の方法で進めてください。",
    opt_approve: "承認して進める",
    opt_approve_text: "はい、そのまま進めてください。",
    opt_pause: "いったん停止",
    opt_pause_text: "いったん作業を止めて、いまの状況を報告してください。",
    opt_report: "進捗を報告",
    opt_report_text: "いまの進捗を1〜2行で報告してください。",
    opt_free: "自由に書く",
    tray_answered: "📨 回答済み — セッションへの反映を待っています",
    tray_head: (name, i, n) => (n > 1 ? `❗ ${name}（${i}/${n}）` : `❗ ${name}`),
    tray_next: "▸ 次へ (J)",
    quick: ["続けて", "この方針でOKです", "テストを直してから push して", "一旦停止して"],
    // シート
    work_now: "▶ いま", work_next: "⏭ 次", work_done: "✅ 完了",
    recent_moves: "最近の動き",
    listen_off: "このセッションはいま受信待機していません。送信は保存され、そのターミナルで次に何か操作した瞬間に届きます（3時間で失効）。",
    listen_off_hint: "受信待機なし — 送っても即座には届きません",
    dialog_head: "💬 セッションのやり取り",
    dialog_empty: "まだ会話がありません",
    dialog_err: "会話を取得できませんでした",
    dialog_older: "▲ もっと見る",
    dialog_oldest: "これより古い会話は表示できません（表示上限）",
    dialog_expand: "⤢ 全画面",
    dialog_modal_head: (n) => `💬 やり取り（${n}件）`,
    crew_head: (n) => `セッション内訳（${n}）`,
    crew_n: (i) => `${i}号`,
    crew_rep: "（代表）",
    target_rep: "宛先: 代表セッション",
    target_n: (i) => `宛先: ${i}号セッション`,
    // 👑ボス
    boss_title: "👑 ボス指令",
    boss_note: "誰に指示を出しますか？",
    // ➕新プロジェクト
    np_opening: "フォルダ選択ダイアログを開いています…（Terminal側に出ます）",
    np_name_ph: "プロジェクト名（例: ブログ編集）",
    np_launch: " Terminal で claude を起動",
    np_go: "入社させる",
    np_joined: (n) => `🎉 ${n} が出勤しました`,
    // 2026-09-08: 起動をチェックしても Terminal が上がらないことがある（Automation の
    // TCC 同意待ち・claude 未インストール等）。**登録できただけ**のときに「出勤しました」と
    // 言うと、空のオフィスを見て行き止まりになる。何が起きたかを分けて伝える。
    np_registered: (n) => `${n} を登録しました（まだ出勤していません）`,
    np_launch_failed: "Terminal を起動できませんでした。そのフォルダで claude を開くと出勤します",
    // 📱スマホ連携
    pair_issuing: "デバイスを発行しています…",
    pair_device_label: "スマホ",
    pair_qr_alt: "ペアリングQR",
    pair_scan: "iPhoneのカメラでQRを読むか、リンクをAirDropで送って開いてください。",
    pair_copy: "ペアリングリンクをコピー",
    pair_copied: "📋 リンクをコピーしました",
    pair_copy_fail: "コピーできませんでした",
    pair_norelay: "中継が未設定です（relay/README.md のデプロイ後にQRが出ます）。デバイスは発行済みです。",
    pair_devices: (n) => `登録済みデバイス（${n}）`,
    pair_revoke: "失効",
    pair_active: (n) => `（有効・あと${n}日）`,
    pair_dead: "（失効済み）",
    pair_revoked: "失効しました",
    // ⚡リソース
    res_note: "API換算の参考値・実際の請求額ではありません",
    res_today: (t, y) => `今日 ${t} tok ≈ ¥${y}`,
    res_used: (plan, pct) => `${plan} ${pct}% 使用`,
    res_reset: (m, d) => `（${m}/${d} リセット）`,
    res_login_yes: "ログイン済み",
    res_login_no: "未ログイン",
    res_connected: "接続済み",
    res_notconnected: "未接続",
    // R72: 課金方式でグループ分け（定額サブスク／APIキー従量）
    res_grp_sub: "💳 サブスクプラン（定額）",
    res_grp_sub_note: "月額・枠内なら追加課金なし",
    res_grp_api_note: "使った分だけ課金",
    res_month: (v) => `今月 ${v}`,
    res_month_since: (v, d) => `今月 ${v}（${d}日〜）`,
    res_nokey: "キー未登録",
    res_spend: "💳 固定費（手動台帳）",
    res_spend_sub: (y, n) => `≈ ¥${y}/月 ・ ${n}件`,
    led_head: "台帳の編集",
    led_name_ph: "名前（例: Claude Max）",
    led_amount_ph: "金額",
    led_renew_ph: "更新日(1-31)",
    led_kind_sub: "サブスク",
    led_kind_payg: "従量",
    led_add: "追加/更新",
    led_saved: "💳 台帳を保存しました",
    led_del: "削除",
    led_deleted: "💳 削除しました",
    led_invalid: "名前と金額を確認してください",
    // 🧾ライセンス系キー（lic_*/feat_*）は R84 全機能無料化で撤去（R85-2）
    // 履歴・ドーナツ
    resend_name: "再送",
    resend_title: "同じ指示をもう一度送る",
    resend_arm: "もう一度で再送",
    hist_wait: "配達待ち", hist_done: "配達済み",
    hist_empty: "まだ指示はありません",
    leg_done: "完了", leg_prog: "進行中", leg_todo: "未着手",
    // 経費ゲージ
    g_today: (label) => `${label} 今日`,
    g_month: (label) => `${label} 今月`,
    g_fixed: "固定費/月",
    g_win_5h: "5時間枠",
    g_win_week: "週間枠",
    g_win_h: (h) => `${h}時間枠`,
    g_remain_d: (d) => `リセットまであと${d}日`,
    g_remain_h: (h) => `リセットまであと${h}時間`,
    g_remain_m: (m) => `リセットまであと${m}分`,
    g_tok_today: (t) => `今日 ${t} tok`,
    g_tok_5h: (t) => `5h ${t} tok`,
    g_live_chip: "実測",
    g_pace_chip: "ペース",
    g_pace_sub: (p) => `基準: 直近7日の5hピーク ${p} tok`,
    g_prev_seen: "前回確認",
    // R63: APIプロバイダ統合コスト
    api_head: "🔌 APIキー（従量課金）",
    api_no_limit: "上限が設定されていません",
    api_balance: (v) => `残高 ${v}`,
    api_nodata: "消費データなし",
    api_err: "取得エラー",
    api_budget_ph: "予算 (例 10)",
    api_budget_save: "設定",
    api_budget_saved: "💳 予算を保存しました",
    api_budget_tag: "（手動予算）",
    api_budget_chip: "予算",
    // オフライン・セットアップ・空オフィス
    off_noconn: "⚠ サーバーに接続できません",
    off_stale: (ago) => `⚠ 接続が切れています — 最終更新 ${ago}（表示は凍結データ）`,
    ago_sec: (s) => `${s}秒前`,
    ago_min: (m) => `${m}分前`,
    setup_hook: "📮 まだ回答が届きません — ターミナルで次の1行を実行すると、この画面からの返信が実際のセッションへ届くようになります",
    setup_hook_cmd: "bash setup.sh",
    setup_hook_copy: "コマンドをコピー",
    setup_hook_copied: "コピーしました",
    sub_line: (n, work, queue, rest) =>
      `${n} プロジェクトが出勤中 — 作業 ${work} · あなた待ち ${queue} · 休憩 ${rest}`,
    sub_line_session: (n, work, queue, rest) =>
      `${n} セッションが出勤中 — 作業 ${work} · あなた待ち ${queue} · 休憩 ${rest}`,
    ob_title: "まだ誰も出勤していません",
    ob_p1: "ターミナルで claude を起動すると、そのプロジェクトが1体のロボットとして出勤します。",
    ob_p2: "左の「➕ 新プロジェクト」からフォルダを選んで、最初のプロジェクトを登録することもできます。",
    ob_demo: "🎬 デモオフィスを見る",
  },
  en: {
    board_title: "Projects",
    digest_title: "While you were away",
    digest_retained: "While you were away (last 90 days recorded)",
    digest_stopped: (n, m) => `❗ Stopped: ${n} robots (longest ${m} min)`,
    digest_completed: (n) => `✅ Completed: ${n} tasks`,
    digest_working: (n) => `▶ Working: ${n} sessions`,
    digest_strip: (away, stopped, done, working) =>
      `Away ${away}: ❗${stopped} ✅${done} ▶${working} — Details`,
    digest_today: "today",
    digest_details: "Details — 20-second replay",
    digest_close: "Close digest (Esc)",
    digest_seen_failed: "Could not save your last visit. The digest may reappear when you reconnect.",
    replay_progress: "20-second replay progress",
    replay_pause: "Pause", replay_resume: "Resume",
    replay_close: "Close replay and return to now (Esc)",
    replay_empty: "There are no replayable events in this period.",
    replay_failed: "Could not load the replay. Please try again.",
    replay_latest: (n) => `Replaying up to the latest ${n} events.`,
    growth_details: "Show XP breakdown",
    growth_total: (xp) => `${xp} XP`,
    growth_tasksDone: (n, xp) => `Completed ${n}×10 = ${xp} XP`,
    growth_commits: (n, xp) => `Commits ${n}×5 = ${xp} XP`,
    growth_asksAnswered: (n, xp) => `❗ Answers ${n}×2 = ${xp} XP`,
    growth_fastAnswers: (n, xp) => `Answers within 5 min bonus ${n}×1 = ${xp} XP`,
    growth_activeMin: (n, xp) => `Active ${n} min÷5 = ${xp} XP`,
    growth_hires: (n, xp) => `Hires ${n}×5 = ${xp} XP`,
    growth_turnsCompleted: (n, xp) => `Codex turns completed ${n}×3 = ${xp} XP`,
    growth_other: (key, n, xp) => `${key} ${n}: ${xp} XP`,
    growth_no_tokens: "XP comes only from the displayed breakdown. Token volume is excluded.",
    growth_unavailable: "The breakdown is unavailable on this connection. View it in your local office.",
    growth_project: "Project",
    growth_level_up: (name, level) => `${name} reached Lv ${level}`,
    board_summary: (n, work, queue, rest) =>
      `${n} sessions on duty — working ${work} · waiting on you ${queue} · resting ${rest}`,
    board_count: (n) => `${n} sessions`,
    board_session: (n) => `Session ${n}`,
    board_level: (n) => `Lv ${n}`,
    board_window_5h: "5h",
    board_working: "Working", board_attention: "Needs you",
    board_waiting: "Waiting", board_resting: "Resting",
    board_no_detail: "No details",
    board_vendor_claude: "Claude", board_vendor_codex: "Codex",
    board_vendor_openclaw: "OpenClaw", board_vendor_other: "Other",
    zone_desk: "At their desk", zone_meeting: "In a meeting", zone_queue: "Waiting on you",
    zone_lounge: "On a break", zone_external: "External (OpenClaw)",
    office_fallback: "AI Office",
    loading: "Loading…",
    gauge_credits: "Credits used",
    gauge_money: "Cost (approx.)",
    btn_newproj: "➕ New project",
    btn_hire: "＋ Add a session",
    hire_where: "① Where",
    hire_choose: "Choose a recent project",
    hire_pick: "Choose a folder",
    hire_picked: "Selected folder",
    hire_pick_note: "Choose a folder previously opened in Claude. For a new folder, run claude there first; it can take about a minute to appear.",
    hire_pick_failed: "No folder was selected. You can choose again.",
    hire_what: "② What",
    hire_prompt: "One-line instruction (1–4000 characters)",
    hire_count: (n) => `${n} / 4000 characters`,
    hire_worktree: "Isolate in a separate branch",
    hire_who: "③ Who",
    hire_claude: "Claude (default)",
    hire_codex: "Codex — use Terminal",
    hire_go: "Start a session",
    hire_starting: "Starting…",
    hire_started: "Started. The session will arrive at the entrance shortly.",
    hire_failed: "Could not confirm startup. Check the session list first. If it has not started, check that the folder is registered and claude is configured before retrying.",
    hire_terminal_note: "To open Terminal, run the following command in your terminal. You can enter your Codex instructions there.",
    hire_terminal_cmd: "open -a Terminal",
    hire_terminal_copy: "Copy the command to open Terminal",
    hire_terminal_copied: "Copied. Paste it into your terminal and run it.",
    hire_new_badge: "🆕",
    hire_branch_badge: (slug) => `⎇ ${slug}`,
    onboarding_questions: "When ❗ appears, use number keys to answer",
    onboarding_dismiss: "When ❗ appears, use number keys to answer (click to dismiss)",
    setup_checklist: "📱 Connection checklist",
    setup_hooks_ready: "✓ Hooks are wired",
    setup_hooks_pending: "○ Hooks are not wired",
    setup_events_ready: "✓ Event recording is wired",
    setup_events_pending: "○ Event recording is not wired",
    setup_events_unknown: "○ Event recording is unconfirmed",
    no3d_list: "Open list mode",
    btn_pair: "📱 Phone pairing",
    btn_run: "▶ What your phone can run",
    no3d: "3D is unavailable here (graphics disabled). You can still review and instruct from the list on the left.",
    tpl_title: "⚡ Quick templates",
    tpl_note: "Save your frequent instructions — one tap here and on 📱 your phone (max 8 · 120 chars)",
    tpl_label_ph: "Label (e.g. Check build)",
    tpl_text_ph: "Text to send (e.g. run verify and report in one line)",
    tpl_add_row: "Add",
    tpl_save: "Save",
    tpl_del: "Delete",
    tpl_saved: "Templates saved (synced to your phone too)",
    run_head: "▶ What your phone can run",
    run_note: "Register the commands your phone may run. For safety they cannot be created or edited from the phone (it can only run what is registered here).",
    run_empty: "Nothing registered yet. Press \"Insert an example\" below for a working template.",
    run_hint: "argv must be an array (no shell strings), cwd must be absolute, returnOutput is none|tail|full (default none = no output leaves your Mac).",
    run_save: "Save",
    run_sample: "Insert an example",
    run_sample_label: "Check git status",
    run_sample_note: "Change cwd to one of your own project paths before saving.",
    run_saved: "Saved",
    btn_res: "⚡ Resources",
    btn_launch: "▶ Launch project",
    launch_note: "Reopen a recent project in Terminal (same list as the phone's ▶).",
    launch_empty: "Nothing to launch yet (start claude once and it appears here).",
    launch_ok: (n) => `▶ Launched ${n}`,
    btn_settings: "⚙ Settings",
    stream_copy: "🎥 Copy streaming URL",
    stream_obs: "OBS (16:9)", stream_short: "Shorts (9:16)", stream_monitor: "Second monitor",
    stream_copied: "Streaming URL copied",
    stream_copy_failed: "Could not copy the URL. Check your browser's clipboard permission.",
    stream_now: (text) => `Now: ${text}`,
    stream_waiting: "Waiting", stream_resting: "Resting", stream_empty: "Waiting for sessions",
    replay_save: "Save today's replay (20-second WebM)",
    replay_record_failed: "Could not save the replay. Please try again.",
    replay_record_cancelled: "Recording cancelled. Keep this page visible while saving.",
    replay_saved: "Replay saved",
    set_theme: "🌙 Theme",
    set_theme_light: "Light",
    set_theme_dark: "Dark",
    set_lang: "🌐 Language",
    relay_head: "📡 Phone relay",
    relay_today: "Used today",
    relay_slowed: " (slowed)",
    relay_throttled: " (throttled)",
    fx_label: "💱 JPY per USD",
    fx_save: "Save",
    fx_saved: "💱 Rate saved",
    snd_title: "Notification sounds",
    sound_ask: "Would you like sound alerts?", sound_yes: "Turn sound on", sound_no: "Don't ask again",
    sound_on: "ON", sound_off: "OFF",
    camera_title: "Layout", camera_compact: "Compact", camera_standard: "Standard", camera_stream: "Broadcast",
    reply_options: "Reply options", reply_save: "Save this reply as a template",
    tpl_existing: (n) => `Saved templates (${n})`, tpl_invalid: "Enter a label and text. You can save up to 8 templates.",
    arch_title: "Hats and accessories", arch_none: "None", arch_phones: "Headphones", arch_cap: "Cap",
    arch_beret: "Beret", arch_pencil: "Pencil", arch_bowtie: "Bow tie", arch_mortar: "Graduation cap",
    arch_headset: "Headset", arch_hardhat: "Hard hat", arch_eyeshade: "Eyeshade",
    arch_readonly: "Accessories cannot be changed in this view.", arch_chat: "Open conversation",
    term_title: "Bring the real terminal to front (double-click a robot works too)",
    term_ok: (app) => `🖥 Brought ${app} to front`,
    term_none: "This member has no local terminal",
    woke: (n) => `▶ ${n} picked up your instruction and is moving`,
    attn_resolved: (n) => `✅ ${n}'s ❗ is resolved`,
    work_head: "📋 Current work",
    qb_head: "⚡ Quick replies",
    keys_head: "🔑 Accounts",
    keys_connect: "Connect",
    keys_change: "Change",
    keys_save: "Save",
    keys_saved: "🔑 Saved",
    keys_ph: "Paste the key (20+ chars)",
    keys_grp_auto: "🅰 Connected automatically (no setup)",
    keys_grp_auto_sub: "Just log in and work in your terminal — usage is recorded automatically.",
    keys_grp_key: "🅱 Connect with an API key",
    keys_grp_key_sub: "Paste each service's API key to fetch balance and spend.",
    keys_badge_auto: "auto",
    keys_now: (e) => `now: ${e}`,
    keys_getfrom: (u) => `Get one at ${u}`,
    keys_revoke: "Remove",
    keys_revoke_arm: "Click again to remove",
    keys_revoked: "🔑 Removed",
    gauges_title: "Click to open accounts & ledger",
    sending: "Sending…",
    sending_busy: "Still sending — one moment",
    updated_ago: (s) => `updated ${s}s ago`,
    hist_more: (n) => `+${n} more`,
    compose_ph: "Type an instruction for this project and press Enter",
    card_tasks: "Task progress",
    card_today: "Today at the office",
    today_sent: "Instructions sent",
    today_attn: "Needs you",
    today_working: "Working",
    today_resting: "On a break",
    today_none: "No instructions sent yet",
    today_last: (a) => `Last instruction ${a}`,
    unit_items: "",
    unit_people: "",
    card_hist: "Recent instructions",
    card_agents: "Projects",
    demo_no_send: "🎬 Demo mode — nothing is sent",
    deliver_ok: (n) => `📨 Delivered to ${n}`,
    deliver_saved: (n) => `📨 Saved for ${n} — it arrives the moment you touch that terminal`,
    send_stalled: (n, m) => `⌨️ ${m} min since you sent and ${n} has not moved — check the terminal`,
    deliver_fail: (m) => `Delivery failed: ${m}`,
    reg_fail: (m) => `Registration failed: ${m}`,
    hs_doing: (act) => `Currently on “${act}”. `,
    hs_question: "There's a question waiting for your answer.",
    hs_approval: (min) => `Stuck on the same step for ${min} min. You can reply from here, but if a permission prompt is open in the terminal it has to be answered there.`,
    hs_meeting: (n) => `In a meeting with ${n} subagents.`,
    hs_lounge: "Work has wrapped up — taking a break in the lounge.",
    hs_external: "An external member running on another machine (OpenClaw).",
    hs_working: "Working.",
    hs_waiting: "Waiting for the next instruction.",
    approval_min: (m) => `Stuck ${m} min`,
    attn_target: (w) => `target: ${w}`,
    opt_text: (label) => `Please go with option "${label}".`,
    answer_sent: (n) => `✅ Your answer reached ${n} — the terminal is moving again`,
    allow_sent: (n) => `✅ Allowed ${n} to run it`,
    ask_live: "The terminal is waiting for your reply right now — answering here reaches it.",
    ask_perm: (tool, what) =>
      `Waiting for permission to run ${tool}${what ? `: ${what}` : ""}`,
    opt_allow: "✅ Allow",
    opt_refuse: "Don't allow",
    opt_refuse_text: "Please don't run that. Find another way.",
    opt_approve: "Approve & continue",
    opt_approve_text: "Yes, please go ahead as planned.",
    opt_pause: "Stop and report",
    opt_pause_text: "Please pause the work and report the current status.",
    opt_report: "Report progress",
    opt_report_text: "Please report your current progress in one or two lines.",
    opt_free: "Write your own",
    tray_answered: "📨 Answered — waiting for the session to catch up",
    tray_head: (name, i, n) => (n > 1 ? `❗ ${name} (${i}/${n})` : `❗ ${name}`),
    tray_next: "▸ Next (J)",
    quick: ["Keep going", "This approach is fine", "Fix the tests, then push", "Pause for now"],
    work_now: "▶ Now", work_next: "⏭ Next", work_done: "✅ Done",
    recent_moves: "Recent activity",
    listen_off: "This session isn't listening right now. Your message is saved and arrives the moment you touch that terminal again (expires in 3 hours).",
    listen_off_hint: "Not listening — it won't arrive right away",
    dialog_head: "💬 Session conversation",
    dialog_empty: "No conversation yet",
    dialog_err: "Couldn't load the conversation",
    dialog_older: "▲ Load earlier",
    dialog_oldest: "Older messages are beyond the display limit",
    dialog_expand: "⤢ Full screen",
    dialog_modal_head: (n) => `💬 Conversation (${n})`,
    crew_head: (n) => `Sessions (${n})`,
    crew_n: (i) => `#${i}`,
    crew_rep: " (lead)",
    target_rep: "To: lead session",
    target_n: (i) => `To: session #${i}`,
    boss_title: "👑 Boss order",
    boss_note: "Who should get the instruction?",
    np_opening: "Opening the folder picker… (it appears on the Terminal side)",
    np_name_ph: "Department name (e.g. Blog Team)",
    np_launch: " Launch claude in Terminal",
    np_go: "Hire",
    np_joined: (n) => `🎉 ${n} joined the office`,
    np_registered: (n) => `${n} is registered (not on duty yet)`,
    np_launch_failed: "Could not launch Terminal. Open claude in that folder to bring it on duty",
    pair_issuing: "Issuing a device…",
    pair_device_label: "Phone",
    pair_qr_alt: "Pairing QR",
    pair_scan: "Scan the QR with your iPhone camera, or AirDrop the link and open it.",
    pair_copy: "Copy pairing link",
    pair_copied: "📋 Link copied",
    pair_copy_fail: "Couldn't copy",
    pair_norelay: "Relay isn't configured yet (the QR appears after deploying relay/ — see relay/README.md). The device itself is issued.",
    pair_devices: (n) => `Registered devices (${n})`,
    pair_revoke: "Revoke",
    pair_active: (n) => ` (active, ${n}d left)`,
    pair_dead: " (revoked)",
    pair_revoked: "Revoked",
    res_note: "Approximate API-equivalent values — not your actual bill",
    res_today: (t, y) => `Today ${t} tok ≈ ¥${y}`,
    res_used: (plan, pct) => `${plan} ${pct}% used`,
    res_reset: (m, d) => ` (resets ${m}/${d})`,
    res_login_yes: "Signed in",
    res_login_no: "Not signed in",
    res_connected: "Connected",
    res_notconnected: "Not connected",
    // R72: grouped by how you pay (flat subscription / metered API key)
    res_grp_sub: "💳 Subscription plans (flat rate)",
    res_grp_sub_note: "Monthly fee — nothing extra inside your quota",
    res_grp_api_note: "Billed for what you use",
    res_month: (v) => `This month ${v}`,
    res_month_since: (v, d) => `This month ${v} (since day ${d})`,
    res_nokey: "No key registered",
    res_spend: "💳 Fixed costs (manual ledger)",
    res_spend_sub: (y, n) => `≈ ¥${y}/mo · ${n} items`,
    led_head: "Edit ledger",
    led_name_ph: "Name (e.g. Claude Max)",
    led_amount_ph: "Amount",
    led_renew_ph: "Renews (1-31)",
    led_kind_sub: "Subscription",
    led_kind_payg: "Pay-per-use",
    led_add: "Add / update",
    led_saved: "💳 Ledger saved",
    led_del: "Delete",
    led_deleted: "💳 Deleted",
    led_invalid: "Check the name and amount",
    resend_name: "Resend",
    resend_title: "Send the same instruction again",
    resend_arm: "press again",
    hist_wait: "Queued", hist_done: "Delivered",
    hist_empty: "No instructions yet",
    leg_done: "Done", leg_prog: "In progress", leg_todo: "Backlog",
    g_today: (label) => `${label} today`,
    g_month: (label) => `${label} this month`,
    g_win_5h: "5-hour window",
    g_win_week: "Weekly window",
    g_win_h: (h) => `${h}h window`,
    g_remain_d: (d) => `resets in ${d}d`,
    g_remain_h: (h) => `resets in ${h}h`,
    g_remain_m: (m) => `resets in ${m}m`,
    g_tok_today: (t) => `today ${t} tok`,
    g_tok_5h: (t) => `5h ${t} tok`,
    g_live_chip: "live",
    g_pace_chip: "pace",
    g_pace_sub: (p) => `vs 7-day 5h peak ${p} tok`,
    g_prev_seen: "last seen",
    api_head: "🔌 API keys (pay as you go)",
    api_no_limit: "No spending limit set",
    api_balance: (v) => `Balance ${v}`,
    api_nodata: "No usage data",
    api_err: "Fetch error",
    api_budget_ph: "Budget (e.g. 10)",
    api_budget_save: "Set",
    api_budget_saved: "💳 Budget saved",
    api_budget_tag: " (manual budget)",
    api_budget_chip: "budget",
    g_fixed: "Fixed/mo",
    off_noconn: "⚠ Can't reach the server",
    off_stale: (ago) => `⚠ Connection lost — last update ${ago} (view is frozen)`,
    ago_sec: (s) => `${s}s ago`,
    ago_min: (m) => `${m}m ago`,
    setup_hook: "📮 Replies aren't being delivered yet — run this one line in a terminal so your answers reach the real session",
    setup_hook_cmd: "bash setup.sh",
    setup_hook_copy: "Copy command",
    setup_hook_copied: "Copied",
    sub_line: (n, work, queue, rest) =>
      `${n} projects on duty — working ${work} · waiting on you ${queue} · resting ${rest}`,
    sub_line_session: (n, work, queue, rest) =>
      `${n} sessions on duty — working ${work} · waiting on you ${queue} · resting ${rest}`,
    ob_title: "Nobody's in the office yet",
    ob_p1: "Start claude in any terminal and that session walks in as a robot.",
    ob_p2: "You can also pick a folder from “➕ New project” on the left to create your first department.",
    ob_demo: "🎬 View the demo office",
  },
};

/** 文言を引く。関数値は引数を渡して評価。未知キーはキー名をそのまま返す（気づける）。 */
export function T(key, ...args) {
  const v = (DICT[LANG] && DICT[LANG][key]) ?? DICT.ja[key];
  if (typeof v === "function") return v(...args);
  return v ?? key;
}

/** ja/en のキー集合（tests/test_strings_parity.py の番人用）。
 *  片方の言語にだけキーを足すと、既定言語jaで生キー名が画面に出る（R85-0で実発生）。 */
export function dictKeys() {
  return { ja: Object.keys(DICT.ja), en: Object.keys(DICT.en) };
}

/** 文字列値だけを返す（R86-C: en に日本語が混じっていないかの番人用。関数値は除外）。 */
export function dictStrings() {
  const pick = (d) => Object.fromEntries(
    Object.entries(d).filter(([, v]) => typeof v === "string"));
  return { ja: pick(DICT.ja), en: pick(DICT.en) };
}
