// ── 新UIの文言辞書（R50提案2c） ──────────────────────────────────
// iso 層内の pure モジュール（DOM・通信・時刻・乱数に触らない）。
// 言語は office_json の lang が正本（apply が setLang する）。データ到着前は
// navigator.language で仮判定する。
//
// 掟: ja の値は既存スモーク（ops/admin/onboard）が文言をピンしているので
//     「1字も変えない」。変えるならスモークとセットで。
let LANG = (typeof navigator !== "undefined" &&
  String(navigator.language || "").toLowerCase().startsWith("ja")) ? "ja" : "en";

export function setLang(l) {
  LANG = l === "en" ? "en" : "ja";
}

export function lang() {
  return LANG;
}

const DICT = {
  ja: {
    // ゾーン
    zone_desk: "自席で作業", zone_meeting: "会議中", zone_queue: "あなた待ち",
    zone_lounge: "休憩中", zone_external: "外部 (OpenClaw)",
    // 静的クローム
    office_fallback: "AIオフィス",
    loading: "読み込み中…",
    gauge_credits: "クレジット消費",
    gauge_money: "コスト（参考）",
    btn_newproj: "➕ 新プロジェクト",
    btn_pair: "📱 スマホ連携",
    btn_res: "⚡ リソース",
    btn_license: "🧾 ライセンス",
    snd_title: "タイプ音",
    term_title: "実ターミナルを前面に表示（ロボのダブルクリックでも）",
    term_ok: (app) => `🖥 ${app} を前面に出しました`,
    term_none: "このメンバーにローカルターミナルはありません",
    woke: (n) => `▶ ${n} が指示を受け取り動き出しました`,
    attn_resolved: (n) => `✅ ${n} の❗が解消しました`,
    work_head: "📋 いまの仕事",
    qb_head: "⚡ 定型",
    keys_head: "🔑 アカウント連携",
    keys_connect: "接続",
    keys_change: "変更",
    keys_save: "保存",
    keys_saved: "🔑 保存しました",
    keys_ph: "キーを貼り付け（20文字以上）",
    keys_grp_auto: "🅰 自動でつながる（設定不要）",
    keys_grp_auto_sub: "ターミナルでログインして使うだけで、消費が自動で記録されます。",
    keys_grp_key: "🅱 APIキーでつなぐ",
    keys_grp_key_sub: "各サービスのAPIキーを貼ると、残高・消費を自動取得します。",
    keys_badge_auto: "自動",
    keys_now: (e) => `いま: ${e}`,
    keys_getfrom: (u) => `発行: ${u}`,
    keys_revoke: "解除",
    keys_revoke_arm: "もう一度で解除",
    keys_revoked: "🔑 解除しました",
    gauges_title: "クリックで連携・台帳を開く",
    sending: "送信中…",
    sending_busy: "送信中です — 少し待ってください",
    updated_ago: (s) => `更新 ${s}秒前`,
    hist_more: (n) => `ほか ${n} 件`,
    compose_ph: "このプロジェクトへ指示を書いて Enter",
    card_tasks: "タスクの進み",
    card_hist: "最近の指示",
    card_agents: "エージェント",
    // 送信・トースト
    demo_no_send: "🎬 デモモード — 投函は行われません",
    deliver_ok: (n) => `📨 ${n} へ配達しました`,
    deliver_fail: (m) => `配達失敗: ${m}`,
    reg_fail: (m) => `登録失敗: ${m}`,
    // humanSummary（シートの1文）
    hs_doing: (act) => `いま「${act}」を進めています。`,
    hs_question: "質問があり、あなたの回答を待っています。",
    hs_approval: (min) => `承認まちが${min}分続いています。ひとこと返すと再開します。`,
    hs_meeting: (n) => `部下${n}体と会議中です。`,
    hs_lounge: "作業が一段落して、ラウンジで休憩中です。",
    hs_external: "別マシン（OpenClaw）で稼働している外部メンバーです。",
    hs_working: "作業中です。",
    hs_waiting: "次の指示を待っています。",
    // ❗トレイ・回答定型文（セッションへ送る本文も言語連動）
    approval_min: (m) => `承認まち ${m}分`,
    attn_target: (w) => `対象: ${w}`,
    opt_text: (label) => `選択肢「${label}」でお願いします。`,
    opt_approve: "承認して続行",
    opt_approve_text: "承認します。このまま進めてください。",
    opt_pause: "一旦停止",
    opt_pause_text: "一旦停止してください。",
    opt_free: "自由に書く",
    tray_answered: "📨 回答済み — セッションへの反映を待っています",
    tray_head: (name, i, n) => (n > 1 ? `❗ ${name}（${i}/${n}）` : `❗ ${name}`),
    tray_next: "▸ 次へ (J)",
    quick: ["続けて", "この方針でOKです", "テストを直してから push して", "一旦停止して"],
    // シート
    work_now: "▶ いま", work_next: "⏭ 次", work_done: "✅ 完了",
    recent_moves: "最近の動き",
    crew_head: (n) => `セッション内訳（${n}）`,
    crew_n: (i) => `${i}号`,
    crew_rep: "（代表）",
    target_rep: "宛先: 代表セッション",
    target_n: (i) => `宛先: ${i}号セッション`,
    // 👑ボス
    boss_title: "👑 ボス指令",
    boss_note: "誰に指示を出しますか？",
    // ➕新プロジェクト
    np_opening: "フォルダ選択ダイアログを開いています…（Terminal側に出ます）",
    np_name_ph: "部署名（例: ブログ編集部）",
    np_gen: " キャラを生成（約$0.4・数分後に反映）",
    np_launch: " Terminal で claude を起動",
    np_go: "入社させる",
    np_joined: (n) => `🎉 ${n} が入社しました`,
    // 📱スマホ連携
    pair_issuing: "デバイスを発行しています…",
    pair_device_label: "スマホ",
    pair_to_license: "🧾 ライセンス登録へ",
    pair_qr_alt: "ペアリングQR",
    pair_scan: "iPhoneのカメラでQRを読むか、リンクをAirDropで送って開いてください。",
    pair_copy: "ペアリングリンクをコピー",
    pair_copied: "📋 リンクをコピーしました",
    pair_copy_fail: "コピーできませんでした",
    pair_norelay: "中継が未設定です（relay/README.md のデプロイ後にQRが出ます）。デバイスは発行済みです。",
    pair_devices: (n) => `登録済みデバイス（${n}）`,
    pair_revoke: "失効",
    pair_revoked: "失効しました",
    // ⚡リソース
    res_note: "API換算の参考値・実際の請求額ではありません",
    res_today: (t, y) => `今日 ${t} tok ≈ ¥${y}`,
    res_used: (plan, pct) => `${plan} ${pct}% 使用`,
    res_reset: (m, d) => `（${m}/${d} リセット）`,
    res_login_yes: "ログイン済み",
    res_login_no: "未ログイン",
    res_connected: "接続済み",
    res_notconnected: "未接続",
    res_spend: "💳 固定費（手動台帳）",
    res_spend_sub: (y, n) => `≈ ¥${y}/月 ・ ${n}件`,
    led_head: "台帳の編集",
    led_name_ph: "名前（例: Claude Max）",
    led_amount_ph: "金額",
    led_renew_ph: "更新日(1-31)",
    led_kind_sub: "サブスク",
    led_kind_payg: "従量",
    led_add: "追加/更新",
    led_saved: "💳 台帳を保存しました",
    led_del: "削除",
    led_deleted: "💳 削除しました",
    led_invalid: "名前と金額を確認してください",
    // 🧾ライセンス
    lic_line: (ed) => `エディション: ${ed}`,
    lic_valid: "（ライセンス有効）",
    lic_none: "（未登録）",
    lic_reason: (r) => `（${r}）`,
    feat_relay: "スマホ連携", feat_push: "Push通知", feat_cost: "コスト", feat_openclaw: "OpenClaw",
    lic_buy: "🚀 Pro を購入 — 近日発売。GitHub を Watch すると発売通知が届きます",
    lic_ph: "ライセンスJSONを貼り付け（購入メールに記載）",
    lic_go: "登録する",
    lic_ok: "✅ 登録しました",
    // 履歴・ドーナツ
    resend_name: "再送",
    resend_title: "同じ指示をもう一度送る",
    resend_arm: "もう一度で再送",
    hist_wait: "配達待ち", hist_done: "配達済み",
    hist_empty: "まだ指示はありません",
    leg_done: "完了", leg_prog: "進行中", leg_todo: "未着手",
    // 経費ゲージ
    g_today: (label) => `${label} 今日`,
    g_fixed: "固定費/月",
    g_win_5h: "5時間枠",
    g_win_week: "週間枠",
    g_win_h: (h) => `${h}時間枠`,
    g_remain_d: (d) => `リセットまであと${d}日`,
    g_remain_h: (h) => `リセットまであと${h}時間`,
    g_remain_m: (m) => `リセットまであと${m}分`,
    g_tok_today: (t) => `今日 ${t} tok`,
    g_tok_5h: (t) => `5h ${t} tok`,
    g_live_chip: "実測",
    ed_badge_openclaw: "OpenClaw Edition",
    lic_upgrade_hybrid: "Hybrid にアップグレードすると、Claude Code のセッションも同じオフィスに表示できます。",
    g_pace_chip: "ペース",
    g_pace_sub: (p) => `基準: 直近7日の5hピーク ${p} tok`,
    g_prev_seen: "前回確認",
    // R63: APIプロバイダ統合コスト
    api_head: "🔌 APIプロバイダ",
    api_no_limit: "上限が設定されていません",
    api_balance: (v) => `残高 ${v}`,
    api_nodata: "消費データなし",
    api_err: "取得エラー",
    api_budget_ph: "予算 (例 10)",
    api_budget_save: "設定",
    api_budget_saved: "💳 予算を保存しました",
    api_budget_tag: "（手動予算）",
    api_budget_chip: "予算",
    // オフライン・セットアップ・空オフィス
    off_noconn: "⚠ サーバーに接続できません",
    off_stale: (ago) => `⚠ 接続が切れています — 最終更新 ${ago}（表示は凍結データ）`,
    ago_sec: (s) => `${s}秒前`,
    ago_min: (m) => `${m}分前`,
    setup_hook: "📮 指示配達が未設定です — ターミナルで bash hooks/install.sh を実行すると、" +
      "回答が実セッションへ届くようになります",
    sub_line: (n, work, queue, rest) =>
      `${n} プロジェクトが出勤中 — 作業 ${work} · あなた待ち ${queue} · 休憩 ${rest}`,
    ob_title: "まだ誰も出勤していません",
    ob_p1: "ターミナルで claude を起動すると、そのセッションがロボットとして出勤します。",
    ob_p2: "左の「➕ 新プロジェクト」からフォルダを選んで、最初の部署を作ることもできます。",
    ob_demo: "🎬 デモオフィスを見る",
  },
  en: {
    zone_desk: "At their desk", zone_meeting: "In a meeting", zone_queue: "Waiting on you",
    zone_lounge: "On a break", zone_external: "External (OpenClaw)",
    office_fallback: "AI Office",
    loading: "Loading…",
    gauge_credits: "Credits used",
    gauge_money: "Cost (approx.)",
    btn_newproj: "➕ New project",
    btn_pair: "📱 Phone pairing",
    btn_res: "⚡ Resources",
    btn_license: "🧾 License",
    snd_title: "Typing sound",
    term_title: "Bring the real terminal to front (double-click a robot works too)",
    term_ok: (app) => `🖥 Brought ${app} to front`,
    term_none: "This member has no local terminal",
    woke: (n) => `▶ ${n} picked up your instruction and is moving`,
    attn_resolved: (n) => `✅ ${n}'s ❗ is resolved`,
    work_head: "📋 Current work",
    qb_head: "⚡ Quick replies",
    keys_head: "🔑 Accounts",
    keys_connect: "Connect",
    keys_change: "Change",
    keys_save: "Save",
    keys_saved: "🔑 Saved",
    keys_ph: "Paste the key (20+ chars)",
    keys_grp_auto: "🅰 Connected automatically (no setup)",
    keys_grp_auto_sub: "Just log in and work in your terminal — usage is recorded automatically.",
    keys_grp_key: "🅱 Connect with an API key",
    keys_grp_key_sub: "Paste each service's API key to fetch balance and spend.",
    keys_badge_auto: "auto",
    keys_now: (e) => `now: ${e}`,
    keys_getfrom: (u) => `Get one at ${u}`,
    keys_revoke: "Remove",
    keys_revoke_arm: "Click again to remove",
    keys_revoked: "🔑 Removed",
    gauges_title: "Click to open accounts & ledger",
    sending: "Sending…",
    sending_busy: "Still sending — one moment",
    updated_ago: (s) => `updated ${s}s ago`,
    hist_more: (n) => `+${n} more`,
    compose_ph: "Type an instruction for this project and press Enter",
    card_tasks: "Task progress",
    card_hist: "Recent instructions",
    card_agents: "Agents",
    demo_no_send: "🎬 Demo mode — nothing is sent",
    deliver_ok: (n) => `📨 Delivered to ${n}`,
    deliver_fail: (m) => `Delivery failed: ${m}`,
    reg_fail: (m) => `Registration failed: ${m}`,
    hs_doing: (act) => `Currently on “${act}”. `,
    hs_question: "There's a question waiting for your answer.",
    hs_approval: (min) => `Waiting for your approval for ${min} min. A quick reply gets it moving again.`,
    hs_meeting: (n) => `In a meeting with ${n} subagents.`,
    hs_lounge: "Work has wrapped up — taking a break in the lounge.",
    hs_external: "An external member running on another machine (OpenClaw).",
    hs_working: "Working.",
    hs_waiting: "Waiting for the next instruction.",
    approval_min: (m) => `Approval wait ${m} min`,
    attn_target: (w) => `target: ${w}`,
    opt_text: (label) => `Please go with option "${label}".`,
    opt_approve: "Approve & continue",
    opt_approve_text: "Approved — keep going.",
    opt_pause: "Pause",
    opt_pause_text: "Please pause for now.",
    opt_free: "Write your own",
    tray_answered: "📨 Answered — waiting for the session to catch up",
    tray_head: (name, i, n) => (n > 1 ? `❗ ${name} (${i}/${n})` : `❗ ${name}`),
    tray_next: "▸ Next (J)",
    quick: ["Keep going", "This approach is fine", "Fix the tests, then push", "Pause for now"],
    work_now: "▶ Now", work_next: "⏭ Next", work_done: "✅ Done",
    recent_moves: "Recent activity",
    crew_head: (n) => `Sessions (${n})`,
    crew_n: (i) => `#${i}`,
    crew_rep: " (lead)",
    target_rep: "To: lead session",
    target_n: (i) => `To: session #${i}`,
    boss_title: "👑 Boss order",
    boss_note: "Who should get the instruction?",
    np_opening: "Opening the folder picker… (it appears on the Terminal side)",
    np_name_ph: "Department name (e.g. Blog Team)",
    np_gen: " Generate a character (≈$0.4 · appears in a few minutes)",
    np_launch: " Launch claude in Terminal",
    np_go: "Hire",
    np_joined: (n) => `🎉 ${n} joined the office`,
    pair_issuing: "Issuing a device…",
    pair_device_label: "Phone",
    pair_to_license: "🧾 Go to license",
    pair_qr_alt: "Pairing QR",
    pair_scan: "Scan the QR with your iPhone camera, or AirDrop the link and open it.",
    pair_copy: "Copy pairing link",
    pair_copied: "📋 Link copied",
    pair_copy_fail: "Couldn't copy",
    pair_norelay: "Relay isn't configured yet (the QR appears after deploying relay/ — see relay/README.md). The device itself is issued.",
    pair_devices: (n) => `Registered devices (${n})`,
    pair_revoke: "Revoke",
    pair_revoked: "Revoked",
    res_note: "Approximate API-equivalent values — not your actual bill",
    res_today: (t, y) => `Today ${t} tok ≈ ¥${y}`,
    res_used: (plan, pct) => `${plan} ${pct}% used`,
    res_reset: (m, d) => ` (resets ${m}/${d})`,
    res_login_yes: "Signed in",
    res_login_no: "Not signed in",
    res_connected: "Connected",
    res_notconnected: "Not connected",
    res_spend: "💳 Fixed costs (manual ledger)",
    res_spend_sub: (y, n) => `≈ ¥${y}/mo · ${n} items`,
    led_head: "Edit ledger",
    led_name_ph: "Name (e.g. Claude Max)",
    led_amount_ph: "Amount",
    led_renew_ph: "Renews (1-31)",
    led_kind_sub: "Subscription",
    led_kind_payg: "Pay-per-use",
    led_add: "Add / update",
    led_saved: "💳 Ledger saved",
    led_del: "Delete",
    led_deleted: "💳 Deleted",
    led_invalid: "Check the name and amount",
    lic_line: (ed) => `Edition: ${ed}`,
    lic_valid: "(license active)",
    lic_none: "(not registered)",
    lic_reason: (r) => ` (${r})`,
    feat_relay: "Phone pairing", feat_push: "Push notifications", feat_cost: "Cost", feat_openclaw: "OpenClaw",
    lic_buy: "🚀 Buy Pro — launching soon. Watch the GitHub repo for the release",
    lic_ph: "Paste your license JSON (from the purchase email)",
    lic_go: "Register",
    lic_ok: "✅ Registered",
    resend_name: "Resend",
    resend_title: "Send the same instruction again",
    resend_arm: "press again",
    hist_wait: "Queued", hist_done: "Delivered",
    hist_empty: "No instructions yet",
    leg_done: "Done", leg_prog: "In progress", leg_todo: "Backlog",
    g_today: (label) => `${label} today`,
    g_win_5h: "5-hour window",
    g_win_week: "Weekly window",
    g_win_h: (h) => `${h}h window`,
    g_remain_d: (d) => `resets in ${d}d`,
    g_remain_h: (h) => `resets in ${h}h`,
    g_remain_m: (m) => `resets in ${m}m`,
    g_tok_today: (t) => `today ${t} tok`,
    g_tok_5h: (t) => `5h ${t} tok`,
    g_live_chip: "live",
    ed_badge_openclaw: "OpenClaw Edition",
    lic_upgrade_hybrid: "Upgrade to Hybrid to see your Claude Code sessions in the same office.",
    g_pace_chip: "pace",
    g_pace_sub: (p) => `vs 7-day 5h peak ${p} tok`,
    g_prev_seen: "last seen",
    api_head: "🔌 API providers",
    api_no_limit: "No spending limit set",
    api_balance: (v) => `Balance ${v}`,
    api_nodata: "No usage data",
    api_err: "Fetch error",
    api_budget_ph: "Budget (e.g. 10)",
    api_budget_save: "Set",
    api_budget_saved: "💳 Budget saved",
    api_budget_tag: " (manual budget)",
    api_budget_chip: "budget",
    g_fixed: "Fixed/mo",
    off_noconn: "⚠ Can't reach the server",
    off_stale: (ago) => `⚠ Connection lost — last update ${ago} (view is frozen)`,
    ago_sec: (s) => `${s}s ago`,
    ago_min: (m) => `${m}m ago`,
    setup_hook: "📮 Delivery isn't set up — run bash hooks/install.sh in a terminal so " +
      "replies reach your real sessions",
    sub_line: (n, work, queue, rest) =>
      `${n} projects on duty — working ${work} · waiting on you ${queue} · resting ${rest}`,
    ob_title: "Nobody's in the office yet",
    ob_p1: "Start claude in any terminal and that session walks in as a robot.",
    ob_p2: "You can also pick a folder from “➕ New project” on the left to create your first department.",
    ob_demo: "🎬 View the demo office",
  },
};

/** 文言を引く。関数値は引数を渡して評価。未知キーはキー名をそのまま返す（気づける）。 */
export function T(key, ...args) {
  const v = (DICT[LANG] && DICT[LANG][key]) ?? DICT.ja[key];
  if (typeof v === "function") return v(...args);
  return v ?? key;
}
