"""R96-D0: GLB→生成ジオメトリ変換器の単体テスト（合成 GLB・stdlib のみ）。"""
import base64, json, os, struct, subprocess, sys, tempfile, unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOOL = ROOT / "tools" / "glb_to_geom.py"
sys.path.insert(0, str(ROOT / "tools"))
import glb_to_geom as g2g  # noqa: E402


def synth_glb(nodes_transform=True, draco=False, node_scale=None, color_factor=None, tilt_normal=False):
    """2 部品: 単位の四角形（2 三角形）を 2 つのノードで置く。1 つは translation+scale 付き。"""
    pos = [(0, 0, 0), (1, 0, 0), (1, 1, 0), (0, 1, 0)]
    nrm = [(0, 0, 1)] * 4 if not tilt_normal else [(0.7071068, 0.7071068, 0)] * 4
    idx = [0, 1, 2, 0, 2, 3]
    buf = bytearray()
    for v in pos: buf += struct.pack("<3f", *v)
    for n in nrm: buf += struct.pack("<3f", *n)
    buf += struct.pack("<6H", *idx)
    while len(buf) % 4: buf += b"\0"
    gltf = {
        "asset": {"version": "2.0"},
        "scene": 0, "scenes": [{"nodes": [0, 1]}],
        "nodes": [{"mesh": 0, "name": "a"},
                  {"mesh": 0, "name": "b", "translation": [2, 0, 0], "scale": node_scale or [2, 2, 2]} if nodes_transform else {"mesh": 0, "name": "b"}],
        "meshes": [{"primitives": [{"attributes": {"POSITION": 0, "NORMAL": 1}, "indices": 2, **({"material": 0} if color_factor else {})}]}],
        **({"materials": [{"pbrMetallicRoughness": {"baseColorFactor": color_factor}}]} if color_factor else {}),
        "accessors": [
            {"bufferView": 0, "componentType": 5126, "count": 4, "type": "VEC3", "min": [0, 0, 0], "max": [1, 1, 0]},
            {"bufferView": 1, "componentType": 5126, "count": 4, "type": "VEC3"},
            {"bufferView": 2, "componentType": 5123, "count": 6, "type": "SCALAR"},
        ],
        "bufferViews": [
            {"buffer": 0, "byteOffset": 0, "byteLength": 48},
            {"buffer": 0, "byteOffset": 48, "byteLength": 48},
            {"buffer": 0, "byteOffset": 96, "byteLength": 12},
        ],
        "buffers": [{"byteLength": len(buf)}],
    }
    if draco:
        gltf["extensionsRequired"] = ["KHR_draco_mesh_compression"]
    js = json.dumps(gltf).encode("utf-8")
    while len(js) % 4: js += b" "
    body = struct.pack("<I4s", len(js), b"JSON") + js + struct.pack("<I4s", len(buf), b"BIN\0") + bytes(buf)
    return struct.pack("<4sII", b"glTF", 2, 12 + len(body)) + body


class GlbToGeomTest(unittest.TestCase):
    def run_tool(self, glb, *args):
        with tempfile.TemporaryDirectory() as d:
            p = Path(d) / "in.glb"; p.write_bytes(glb)
            out = Path(d) / "gen"
            r = subprocess.run([sys.executable, str(TOOL), str(p), "--name", "probe", "--out", str(out), *args],
                               capture_output=True, text=True)
            js = (out / "probe.js").read_text(encoding="utf-8") if (out / "probe.js").exists() else None
            return r, js

    def test_parts_positions_and_world_transform(self):
        r, js = self.run_tool(synth_glb())
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertTrue(js.startswith("// generated by tools/glb_to_geom.py"))
        mod = json.loads(js.split("export default ", 1)[1].rstrip().rstrip(";"))
        self.assertEqual(mod["name"], "probe")
        self.assertEqual(len(mod["parts"]), 2)
        self.assertEqual(mod["tris"], 4)
        # bbox は 2 部品のワールド座標（b は translation 2 + scale 2 → x 2..4, y 0..2）
        lo, hi = mod["bbox"]
        self.assertAlmostEqual(lo[0], 0, places=3); self.assertAlmostEqual(hi[0], 4, places=3)
        self.assertAlmostEqual(hi[1], 2, places=3)
        # 量子化の逆変換で頂点が元の位置へ戻る（Int16 の 1 目盛り以内）
        part_b = [p for p in mod["parts"] if p["name"] == "b"][0]
        q = struct.unpack("<%dh" % (part_b["n"] * 3), base64.b64decode(part_b["pos"]))
        xs = [q[i] * mod["scale"] + mod["offset"][0] for i in range(0, len(q), 3)]
        self.assertAlmostEqual(min(xs), 2, delta=mod["scale"] * 2)
        self.assertAlmostEqual(max(xs), 4, delta=mod["scale"] * 2)
        idx = struct.unpack("<%dH" % (part_b["tri"] * 3), base64.b64decode(part_b["idx"]))
        self.assertLess(max(idx), part_b["n"])
        self.assertNotIn("col", part_b)   # 焼き色を頼んでいない

    def test_rejects_draco_and_gates(self):
        r, js = self.run_tool(synth_glb(draco=True))
        self.assertNotEqual(r.returncode, 0); self.assertIsNone(js)
        self.assertIn("Draco", r.stderr + r.stdout)
        r, js = self.run_tool(synth_glb(), "--max-tris", "3")
        self.assertNotEqual(r.returncode, 0); self.assertIsNone(js)

    def test_nonuniform_scale_keeps_normals_perpendicular(self):
        # 別モデルレビュー（2026-09-15）: 位置と同じ行列で法線を変換すると非一様スケールで面に垂直でなくなる。
        r, js = self.run_tool(synth_glb(node_scale=[2, 1, 1], tilt_normal=True))
        self.assertEqual(r.returncode, 0, r.stderr)
        mod = json.loads(js.split("export default ", 1)[1].rstrip().rstrip(";"))
        part_b = [p for p in mod["parts"] if p["name"] == "b"][0]
        n = struct.unpack("<%db" % (part_b["n"] * 3), base64.b64decode(part_b["nrm"]))
        nx, ny = n[0] / 127, n[1] / 127
        # 逆転置: (0.707,0.707,0) をスケール [2,1,1] で変換 → (0.447, 0.894, 0)
        self.assertAlmostEqual(nx, 0.447, delta=0.03); self.assertAlmostEqual(ny, 0.894, delta=0.03)

    def test_bake_color_without_uv_uses_base_color_factor_in_linear_space(self):
        r, js = self.run_tool(synth_glb(color_factor=[0.5, 0.0, 1.0, 1.0]), "--bake-color")
        self.assertEqual(r.returncode, 0, r.stderr)
        mod = json.loads(js.split("export default ", 1)[1].rstrip().rstrip(";"))
        part = mod["parts"][0]
        self.assertIn("col", part)
        c = base64.b64decode(part["col"])
        self.assertEqual(len(c), part["n"] * 3)
        # リニア 0.5 → sRGB 188（127 ではない）・0 → 0・1 → 255
        self.assertEqual((c[0], c[1], c[2]), (188, 0, 255))

    def test_top_prefers_the_highest_large_upward_surface(self):
        # ソファ型: 大きな受け板（y=0.3）の上に小さめのクッション面（y=0.5・面積 40%）→ 天板は上の面。
        # 参照点: 面積 10% の小さな面（y=0.9）は無視する。
        glb = synth_glb(nodes_transform=False)
        r, js = self.run_tool(glb)
        self.assertEqual(r.returncode, 0, r.stderr)
        sys.path.insert(0, str(ROOT / "tools"))
        import glb_to_geom as g
        big = [(0, .3, 0), (1, .3, 0), (1, .3, 1), (0, .3, 1)]
        mid = [(0, .5, 0), (.632, .5, 0), (.632, .5, .632), (0, .5, .632)]     # 面積 0.4
        tiny = [(0, .9, 0), (.316, .9, 0), (.316, .9, .316), (0, .9, .316)]  # 面積 0.1
        parts = [{"pos": big + mid + tiny, "idx": [0, 2, 1, 0, 3, 2, 4, 6, 5, 4, 7, 6, 8, 10, 9, 8, 11, 10]}]
        top = g.top_surface(parts, [[0, 0, 0], [1, 1, 1]])
        self.assertAlmostEqual(top, .5, delta=.03)

    def test_mirrored_scale_flips_winding(self):
        # 反転スケールでは頂点順も反転する（面の向き＝法線と一致・片面描画で消えない）
        r, js = self.run_tool(synth_glb(node_scale=[-1, 1, 1]))
        self.assertEqual(r.returncode, 0, r.stderr)
        mod = json.loads(js.split("export default ", 1)[1].rstrip().rstrip(";"))
        a = [p for p in mod["parts"] if p["name"] == "a"][0]; b = [p for p in mod["parts"] if p["name"] == "b"][0]
        ia = struct.unpack("<%dH" % (a["tri"] * 3), base64.b64decode(a["idx"]))
        ib = struct.unpack("<%dH" % (b["tri"] * 3), base64.b64decode(b["idx"]))
        self.assertEqual(ia[:3], (0, 1, 2)); self.assertEqual(ib[:3], (0, 2, 1))

    def test_dry_run_writes_nothing(self):
        r, js = self.run_tool(synth_glb(), "--dry")
        self.assertEqual(r.returncode, 0, r.stderr); self.assertIsNone(js)
        self.assertIn("tris=4", r.stderr + r.stdout)


if __name__ == "__main__":
    unittest.main()
