// R98-W2: Claude（丸頭＋アンテナ 1 本・クリームの殻）の文字グリッド＝**基準セル**。
// 1 文字 = 1 ドット（凡例は ./palette.js）。16×24・側面視・右向き（左向きは描画側が反転する）。
// 残り 12 コマ × 3 ベンダーはこの形に揃える（type / walk×4 / raise×2 / think / rest×2 / done）。
// 起こし方= 矩形指定から機械で組む（この 2 枚）か tools/px_quantize.py（生成画像 → 量子化）。
// 番人= tools/px_lint.py（寸法・凡例・色数 ≤8・左右の枠に触れない・コマ表・歩行の差）。
export const CLAUDE = Object.freeze({
  idle0: [
    ".......a........",
    ".......o........",
    "..oooooooooooo..",
    "..osssssssssso..",
    "..ossssssffffo..",
    "..ossssssffffo..",
    "..ossssssfeefo..",
    "..ossssssffffo..",
    "..ossssssffffo..",
    "..osssssssssso..",
    "..ohssssssssso..",
    "..oooooooooooo..",
    "...oooooooooo...",
    "...osssssssso...",
    "...osssssssso...",
    "...osssssBBsoo..",
    "...ossssssssoh..",
    "...oaaassssso...",
    "...oaaassssso...",
    "...oooooooooo...",
    ".....oo..oo.....",
    ".....oo..oo.....",
    ".....oo..oo.....",
    ".....ho..ho.....",
  ],
  idle1: [
    "................",
    ".......a........",
    ".......o........",
    "..oooooooooooo..",
    "..osssssssssso..",
    "..ossssssffffo..",
    "..ossssssffffo..",
    "..ossssssfeefo..",
    "..ossssssffffo..",
    "..ossssssffffo..",
    "..osssssssssso..",
    "..ohssssssssso..",
    "..oooooooooooo..",
    "...oooooooooo...",
    "...osssssssso...",
    "...osssssssso...",
    "...osssssBBsoo..",
    "...ossssssssoh..",
    "...oaaassssso...",
    "...oaaassssso...",
    "...oooooooooo...",
    ".....oo..oo.....",
    ".....oo..oo.....",
    ".....ho..ho.....",
  ],
});
