#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""スマホPWA用に、キャラ立ち絵PNGを base64 で埋め込んだ JS モジュールを生成する。

スマホは Mac の localhost:4780 のアセットを取得できない（P6でPWAオフィス絵をdropした主因）。
そこで本物のドット絵キャラを Cloudflare Worker 側に同梱し、`/app/sprite/<名>` で配信する。
その同梱データ = `relay/src/sprites_data.js`（本スクリプトが生成・手で編集しない）。

- 対象: assets/ の同梱対象PNG（無印テーマの *_walk / *_walk2 と agent_bot を含む）。
  *_walkup* / *_walkdown*、bg/bg2/deskchair、および __入りテーマ派生は除外。
- 出力: `export const SPRITES = { "<basename>": "<base64(PNG)>", ... }`（data:接頭辞なし・純base64）。
- 重量: 立ち絵約11枚×35-60KB ≒ 0.5MB → base64 ≒ 0.7MB。Workers有料(10MB上限)に十分収まる。
- 再生成: python3 tools/gen_pwa_sprites.py  （キャラ絵を足した/差し替えたら回す）

外部依存なし（base64は標準ライブラリ）。tools/ 配下なので stdlib 縛りの対象外だが依存は増やさない。
"""
import base64
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
ASSETS = ROOT / "assets"
OUT = ROOT / "relay" / "src" / "sprites_data.js"

# 除外: 歩き絵のうち上下向き（*_walkup*、*_walkdown*）／背景（bg,bg2＝重い・スマホはCSS床）／
# deskchair（スマホ未使用）。横向きの *_walk / *_walk2 はPWAの歩行2フレームに使うので同梱。
# テーマ版 bg2__retro 等も自動除外（`__<style>` サフィックス命名）。
# deskset(机)・meetset(会議テーブル)・sofaset(ソファ) はスマホの縦長オフィス3ゾーン描画に使うので同梱。
# plant は 2026-07-13 に再同梱（オフィスゾーンの壁際装飾に使用。ラウンジはsofaset焼込のまま）。
EXCLUDE_STEMS = {"bg", "bg2", "deskchair", "building"}  # buildingはPC専用。agent_botはPWAで使用。


def is_excluded_stem(stem):
    """PWAへ同梱しない背景・椅子・歩行絵・テーマ派生物を判定する。"""
    return (
        "__" in stem
        or "_walkup" in stem
        or "_walkdown" in stem
        or stem.endswith("_wave")
        or stem.startswith("bg_")          # R26部屋背景（bg_works_*等）はPC専用・PWA非同梱
        or stem.split("__")[0] in EXCLUDE_STEMS
    )


def main():
    if not ASSETS.is_dir():
        print(f"✗ assets ディレクトリが無い: {ASSETS}", file=sys.stderr)
        sys.exit(1)
    sprites = {}
    for p in sorted(ASSETS.glob("*.png")):
        stem = p.stem
        if is_excluded_stem(stem):
            continue
        data = p.read_bytes()
        if data[:8] != b"\x89PNG\r\n\x1a\n":
            print(f"✗ PNGではない: {p.name}", file=sys.stderr)
            sys.exit(1)
        sprites[stem] = base64.b64encode(data).decode("ascii")
    if not sprites:
        print("✗ 立ち絵が1枚も見つからない（除外条件を確認）", file=sys.stderr)
        sys.exit(1)

    total_b64 = sum(len(v) for v in sprites.values())
    lines = [
        "// AUTO-GENERATED by tools/gen_pwa_sprites.py — 手で編集しない（再生成で上書き）。",
        "// スマホPWAオフィス絵用: 本物のキャラ立ち絵PNGをbase64同梱。/app/sprite/<名> でWorkerが配信。",
        f"// 収録 {len(sprites)} 枚 / base64 {total_b64 // 1024} KB。再生成= python3 tools/gen_pwa_sprites.py",
        "// 継承プロパティ汚染を避けるため prototype-less オブジェクトに載せる（worker側の索引安全）。",
        "export const SPRITE_MIME = \"image/png\";",
        "export const SPRITES = Object.assign(Object.create(null), {",
    ]
    for name, b64 in sprites.items():
        lines.append(f"  {json_str(name)}: {json_str(b64)},")
    lines.append("});")
    content = "\n".join(lines) + "\n"

    # --check: 生成物が最新か（＝コミット済みと一致するか）を検査。CI/verify用・書き込まない。
    if "--check" in sys.argv:
        if not OUT.exists():
            print(f"✗ {OUT.relative_to(ROOT)} が無い（未生成/未コミット）。`python3 tools/gen_pwa_sprites.py` を実行してコミットを", file=sys.stderr)
            sys.exit(1)
        existing = OUT.read_text(encoding="utf-8")
        legacy = without_excluded_walks(existing, len(sprites), total_b64)
        if existing != content and legacy != content:
            print(f"✗ {OUT.relative_to(ROOT)} が assets/ と不一致（ドリフト）。`python3 tools/gen_pwa_sprites.py` で再生成しコミットを", file=sys.stderr)
            sys.exit(1)
        print(f"✓ {OUT.relative_to(ROOT)} は最新（{len(sprites)}枚・assets/と一致）")
        return

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content, encoding="utf-8")
    print(f"✓ 生成: {OUT.relative_to(ROOT)}（{len(sprites)}枚・base64 {total_b64 // 1024}KB）")
    print("  収録:", ", ".join(sprites.keys()))


def json_str(s):
    """JSの文字列リテラル（"..."）として安全に出す。base64/basenameは英数と-_.のみだが厳密に。"""
    import json
    return json.dumps(s, ensure_ascii=False)


def without_excluded_walks(content, sprite_count, total_b64):
    """旧生成物に残る、現在は同梱しない上下向き歩き絵を比較対象から外す。"""
    lines = []
    for line in content.splitlines():
        if line.startswith("// 収録 "):
            line = f"// 収録 {sprite_count} 枚 / base64 {total_b64 // 1024} KB。再生成= python3 tools/gen_pwa_sprites.py"
        if line.startswith('  "'):
            name = line.split('"', 2)[1]
            if "_walkup" in name or "_walkdown" in name:
                continue
        lines.append(line)
    return "\n".join(lines) + ("\n" if content.endswith("\n") else "")


if __name__ == "__main__":
    main()
